# -*- coding: utf-8 -*-
"""Project 1 - Build a Dash App.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o5RFIH5O97hr9Uy2JRWAJDzzQOPhnr4R

https://colab.research.google.com/
"""
import dash
from dash import dcc
from dash import html
import plotly.express as px

df = px.data.tips()


app = dash.Dash()

from dash.dependencies import Input, Output

app.layout = html.Div([
                       html.H1("My Dash App"),
                       html.P("Welcome."),
                       dcc.Graph(id='graph'),
                       html.Label([
                                   "colorscale",
                                   dcc.Dropdown(
                                       id="colorscale-dropdown",
                                       clearable=False,
                                       value="plasma",
                                       options=[
                                                {"label": color, "value": color}
                                                for color in px.colors.named_colorscales()
                                       ])
                       ])
])

@app.callback(
    Output("graph", "figure"),
    [Input("colorscale-dropdown", "value")]
)

def update_figure(colorscale):
  return px.scatter(
      df,
      x="total_bill",
      y="tip",
      color="size",
      color_continuous_scale=colorscale,
      render_mode="webgl",
      title="Y vs X"
  )

if __name__ == '__main__':
    app.run_server()